Repository PatrickNiyogitare28/customify, pull requests merged in 2021-03, with the labels that each got.

#65 Tracy
  .idea/customify.iml
  .idea/misc.xml
  .idea/workspace.xml
  customify.iml
  src/com/customify/client/Keys.java
  src/com/customify/client/Login.java
  src/com/customify/client/dashboards/com/customify/client/dashboards/BusinessAdminDashboard.java
  src/com/customify/client/services/AuthService.java
  src/com/customify/client/services/CustomerService.java
  src/com/customify/client/views/customer/CustomerMainView.java
  src/com/customify/client/views/customer/DisableCustomerView.java
  src/com/customify/client/views/customer/ReEnableCustomer.java
  src/com/customify/client/views/customer/ReEnableCustomerView.java
  src/com/customify/server/Keys.java
  src/com/customify/server/services/CustomerService.java
  src/com/customify/server/utils/PrepareJson.java
  src/com/customify/server/utils/RequestHandler.java
Labels: Not ready

#67 Everything working on the menu related to the businesses
  src/com/customify/client/dashboards/SuperAdminDashboard.java
  src/com/customify/client/services/BusinessService.java
  src/com/customify/client/utils/authorization/files/Employee.csv
  src/com/customify/client/utils/authorization/files/SuperAdmin.csv
  src/com/customify/client/views/Business/BusinessEditView.java
  src/com/customify/client/views/Business/BusinessRegisterView.java
  src/com/customify/client/views/Business/BusinessView.java
  src/com/customify/server/services/BusinessService.java
Labels: Ready

#72 Everything related to Business module Now Working
  src/com/customify/client/Main.java
  src/com/customify/client/services/AuthService.java
  src/com/customify/client/services/BusinessService.java
  src/com/customify/client/services/ProductService.java
  src/com/customify/client/views/AwardMangment/CouponView.java
  src/com/customify/client/views/Business/BusinessReadView.java
  src/com/customify/client/views/Business/BusinessView.java
  src/com/customify/client/views/Home.java
  src/com/customify/client/views/customer/CustomerMainView.java
  src/com/customify/server/data_format/business/BusinessRFormat.java
  src/com/customify/server/services/BusinessService.java
  src/com/customify/server/utils/ConnectionHandler.java
Labels: Ready

#75 Aimelyse
  customify.iml
  src/com/customify/server/models/billing/BillingModel.java
  src/com/customify/server/models/billing/FeatureModel.java
  src/com/customify/server/models/billing/PlanModel.java
  src/com/customify/server/response_data_format/billing/BillingFormat.java
  src/com/customify/server/response_data_format/billing/FeatureFormat.java
  src/com/customify/server/response_data_format/billing/PlanFormat.java
  src/com/customify/server/response_data_format/report/CustomerReportFormat.java
  src/com/customify/server/response_data_format/report/QuantityReportFormat.java
  src/com/customify/server/response_data_format/report/SaleReportFormat.java
  src/com/customify/server/services/billing/BillingService.java
  src/com/customify/server/services/reports/CustomerReportService.java
Labels: Ready

#76 Product management working fine
  src/com/customify/client/Keys.java
  src/com/customify/client/dashboards/BusinessAdminDashboard.java
  src/com/customify/client/dashboards/EmployeeDashboard.java
  src/com/customify/client/services/CustomerFeedbackService.java
  src/com/customify/client/services/CustomerService.java
  src/com/customify/client/services/ProductService.java
  src/com/customify/client/utils/authorization/files/Employee.csv
  src/com/customify/client/utils/authorization/files/SuperAdmin.csv
  src/com/customify/client/views/ProductView.java
  src/com/customify/server/Keys.java
  src/com/customify/server/response_data_format/products/GetAllProductsFormat.java
  src/com/customify/server/services/ProductService.java
  src/com/customify/server/utils/RequestHandler.java
Labels: Ready

#63 Ft implementation of features
  .idea/workspace.xml
  src/com/customify/client/Keys.java
  src/com/customify/client/dashboards/SuperAdminDashboard.java
  src/com/customify/client/data_format/billing/DeleteFeatureFormat.java
  src/com/customify/client/data_format/billing/FeatureFormat.java
  src/com/customify/client/data_format/billing/GetFeatureByIdFormat.java
  src/com/customify/client/data_format/billing/GetFeaturesFormat.java
  src/com/customify/client/data_format/billing/UpdatedFeatureFormat.java
  src/com/customify/client/services/BillingService.java
  src/com/customify/client/services/FeatureService.java
  src/com/customify/client/services/FeaturesService.java
  src/com/customify/client/utils/authorization/files/Employee.csv
  src/com/customify/client/utils/authorization/files/SuperAdmin.csv
  src/com/customify/client/views/billing/BillingView.java
  src/com/customify/client/views/billing/FeaturesView.java
  src/com/customify/client/views/billing/PlansView.java
  src/com/customify/server/Keys.java
  src/com/customify/server/SendToClient.java
  src/com/customify/server/data_format/billing/FeatureFormat.java
  src/com/customify/server/models/BillingModel.java
  src/com/customify/server/response_data_format/billing/ResponseStatus.java
  src/com/customify/server/services/billing/FeatureService.java
  src/com/customify/server/utils/RequestHandler.java
  workspace.xml
Labels: Not ready

#90 Fredson
  src/com/customify/server/services/NotificationService.java
  src/com/customify/server/services/PointsService.java
Labels: Ready

#92 Fredson
  src/com/customify/client/dashboards/EmployeeDashboard.java
  src/com/customify/client/utils/authorization/files/Admin.csv
  src/com/customify/client/utils/authorization/files/Employee.csv
  src/com/customify/server/data_format/sales/SaleDataFormat.java
  src/com/customify/server/response_data_format/sale/SaleDataFormat.java
  src/com/customify/server/services/NotificationService.java
  src/com/customify/server/services/PointsService.java
  src/com/customify/server/services/SalesService.java
  src/com/customify/server/utils/RequestHandler.java
Labels: Very Ready

#97 Mailing customers on new products.
  src/com/customify/client/utils/authorization/files/Employee.csv
  src/com/customify/client/views/ProductView.java
  src/com/customify/server/services/NotificationService.java
  src/com/customify/server/services/ProductService.java
  src/com/customify/server/utils/MailCustomers.java
  src/com/customify/server/utils/RequestHandler.java
Labels: Ready
